### ISSUE TITLE
Compile error with caffe: accuracy_coeff_layer is not added in caffe.proto

### ISSUE THREAD

**Issue by Jeromexin** [hyojinie/crn#1]
Compile error with caffe as below:

CXX src/caffe/solvers/adam_solver.cpp
src/caffe/layers/accuracy_coeff_layer.cpp: In instantiation of 'void caffe::AccuracyCoeffLayer<Dtype>::LayerSetUp(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = float]':
src/caffe/layers/accuracy_coeff_layer.cpp:105:1:   required from here
src/caffe/layers/accuracy_coeff_layer.cpp:13:10: error: 'class caffe::LayerParameter' has no member named 'accuracy_coeff_param'
   top_k_ = this->layer_param_.accuracy_coeff_param().top_k();
          ^
src/caffe/layers/accuracy_coeff_layer.cpp:15:21: error: 'class caffe::LayerParameter' has no member named 'accuracy_coeff_param'
   has_ignore_label_ =
                     ^
src/caffe/layers/accuracy_coeff_layer.cpp:18:19: error: 'class caffe::LayerParameter' has no member named 'accuracy_coeff_param'
     ignore_label_ = this->layer_param_.accuracy_coeff_param().ignore_label();
                   ^
src/caffe/layers/accuracy_coeff_layer.cpp: In instantiation of 'void caffe::AccuracyCoeffLayer<Dtype>::Reshape(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = float]':
src/caffe/layers/accuracy_coeff_layer.cpp:105:1:   required from here
src/caffe/layers/accuracy_coeff_layer.cpp:27:15: error: 'class caffe::LayerParameter' has no member named 'accuracy_coeff_param'
   label_axis_ =
               ^
src/caffe/layers/accuracy_coeff_layer.cpp: In instantiation of 'void caffe::AccuracyCoeffLayer<Dtype>::LayerSetUp(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = double]':
src/caffe/layers/accuracy_coeff_layer.cpp:105:1:   required from here
src/caffe/layers/accuracy_coeff_layer.cpp:13:10: error: 'class caffe::LayerParameter' has no member named 'accuracy_coeff_param'
   top_k_ = this->layer_param_.accuracy_coeff_param().top_k();
          ^
src/caffe/layers/accuracy_coeff_layer.cpp:15:21: error: 'class caffe::LayerParameter' has no member named 'accuracy_coeff_param'
   has_ignore_label_ =
                     ^
src/caffe/layers/accuracy_coeff_layer.cpp:18:19: error: 'class caffe::LayerParameter' has no member named 'accuracy_coeff_param'
     ignore_label_ = this->layer_param_.accuracy_coeff_param().ignore_label();
                   ^
src/caffe/layers/accuracy_coeff_layer.cpp: In instantiation of 'void caffe::AccuracyCoeffLayer<Dtype>::Reshape(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = double]':
src/caffe/layers/accuracy_coeff_layer.cpp:105:1:   required from here
src/caffe/layers/accuracy_coeff_layer.cpp:27:15: error: 'class caffe::LayerParameter' has no member named 'accuracy_coeff_param'
   label_axis_ =
               ^
make: *** [.build_release/src/caffe/layers/accuracy_coeff_layer.o] Error 1
make: *** Waiting for unfinished jobs...._

It seems that the new layer accuracy_coeff_layer is not added in caffe.proto. 
After adding "optional AccuracyCoeffParameter accuracy_coeff_param = 150;" in caffe.proto, caffe is compiled successfully.

Moreover, I want train this mode on my own dataset.  Can you provide the pre-processing script?

**Comment by hyojinie** [comment]
Oh, you can just remove the accuracy_coeff_layer.cpp that is not related to this project. If you would like to train on your own dataset, I am afraid you should create your own. The model definition is given, so it should be straightforward.
